### ISSUE TITLE
ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task

### ISSUE THREAD

**Issue by learningmate123** [Hygieia/hygieia-codequality-sonar-collector#27]
[taskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_222]
        at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_222]
        at com.capitalone.dashboard.collector.SonarCollectorTask.collect(SonarCollectorTask.java:102) ~[sonar-codequality-collector.jar!/:3.1.3-SNAPSHOT]
        at com.capitalone.dashboard.collector.SonarCollectorTask.collect(SonarCollectorTask.java:39) ~[sonar-codequality-collector.jar!/:3.1.3-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.1.11.jar!/:3.1.3-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]

**Comment by sukhdevkhade** [comment]
hi @learningmate123  ...facing the similar problem ..please explain how to resolved .
